image: java:8

stages:
  - build

before_script:
  - chmod +x mvnw

build:
  stage: build
  script:
    - ./mvnw verify
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml