server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hafenkran
    username: hafenkran
    password: test
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  auth-validity: 172800
  refresh-validity: 300
  secret: MCgCIQCAS7IFlSvaBOPXwSBHo+7+6C4RbkvYj3fgI5+Abe4pRwIDAQAB

mockdata: true

service-user:
  name: service
  password: test

cluster-service-uri: http://localhost:8082