server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hafenkran
    username: hafenkran
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  validity: 18000
  secret: MCgCIQCAS7IFlSvaBOPXwSBHo+7+6C4RbkvYj3fgI5+Abe4pRwIDAQAB